name: cvae_env
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8  # Specify the Python version
  - pytorch=2.1.0  # Updated to the latest stable version
  - torchvision=0.16.0  # Updated version compatible with PyTorch 2.1.0
  - cudatoolkit  # Updated to match your CUDA version
  - numpy
  - scipy
  - matplotlib  # For plotting and visualization
  - pandas  # If you are dealing with tabular data
  - jupyter  # For Jupyter notebooks, if you use them
  - pip
  - pip:
      - torchinfo  # For detailed model summaries (optional)
